name: tp
services:

  # ============================== RABBITMQ SERVICE ============================== #

  rabbitmq-message-middleware:
    image: "rabbitmq:4-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - custom_net
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ============================== CLIENT & SERVER SERVICES ============================== #

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 -m client.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CLIENT_ID=0
      - SERVER_HOST=server
      - SERVER_PORT=5000
      - DATA_PATH=/data
      - RESULTS_PATH=/results
      - BATCH_MAX_SIZE=20
    networks:
      - custom_net
    volumes:
      - type: bind
        source: ./.data
        target: /data
        read_only: true
      - type: bind
        source: ./.results
        target: /results
        read_only: false
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      server:
        condition: service_started

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 -m server.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - SERVER_PORT=5000
      - SERVER_LISTEN_BACKLOG=5
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - MENU_ITEMS_CLN_AMOUNT=1
      - STORES_CLN_AMOUNT=1
      - TRANSACTION_ITEMS_CLN_AMOUNT=1
      - TRANSACTIONS_CLN_AMOUNT=1
      - USERS_CLN_AMOUNT=1
      - Q1X_OB_AMOUNT=1
      - Q21_OB_AMOUNT=1
      - Q22_OB_AMOUNT=1
      - Q3X_OB_AMOUNT=1
      - Q4X_OB_AMOUNT=1
    networks:
      - custom_net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  # ============================== CLEANERS SERVICES ============================== #

  menu_items_cleaner_items_0:
    container_name: menu_items_cleaner_items_0
    image: menu_items_cleaner:latest
    entrypoint: python3 -m controllers.cleaners.menu_items_cleaner.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CLEANER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - JOINS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  stores_cleaner_items_0:
    container_name: stores_cleaner_items_0
    image: stores_cleaner:latest
    entrypoint: python3 -m controllers.cleaners.stores_cleaner.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CLEANER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - JOINS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  transaction_items_cleaner_0:
    container_name: transaction_items_cleaner_0
    image: transaction_items_cleaner:latest
    entrypoint: python3 -m controllers.cleaners.transaction_items_cleaner.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CLEANER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - FILTERS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  transactions_cleaner_0:
    container_name: transactions_cleaner_0
    image: transactions_cleaner:latest
    entrypoint: python3 -m controllers.cleaners.transactions_cleaner.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CLEANER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - FILTERS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  users_cleaner_0:
    container_name: users_cleaner_0
    image: users_cleaner:latest
    entrypoint: python3 -m controllers.cleaners.users_cleaner.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CLEANER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - JOINS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

      # ============================== FILTERS SERVICES ============================== #
      
  filter_transactions_by_year_0:
    container_name: filter_transactions_by_year_0
    image: filter_transactions_by_year:latest
    entrypoint: python3 -m controllers.filters.filter_transactions_by_year.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CONTROLLER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - PREV_CONTROLLERS_AMOUNT=1
      - FILTERS_AMOUNT=1
      - YEARS=2024,2025
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  filter_transactions_by_hour_0:
    container_name: filter_transactions_by_hour_0
    image: filter_transactions_by_hour:latest
    entrypoint: python3 -m controllers.filters.filter_transactions_by_hour.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CONTROLLER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - PREV_CONTROLLERS_AMOUNT=1
      - FILTERS_AMOUNT=1
      - MIN_HOUR=6
      - MAX_HOUR=23
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  filter_transactions_by_final_amount_0:
    container_name: filter_transactions_by_final_amount_0
    image: filter_transactions_by_final_amount:latest
    entrypoint: python3 -m controllers.filters.filter_transactions_by_final_amount.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - CONTROLLER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - PREV_CONTROLLERS_AMOUNT=1
      - OUTPUT_BUILDERS_AMOUNT=1
      - MIN_FINAL_AMOUNT=75.0
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  # filter_items_by_year_0:
  #   container_name: filter_items_by_year_0
  #   image: filter_items_by_year:latest
  #   entrypoint: python3 -m controllers.filters.filter_items_by_year.main
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - LOGGING_LEVEL=INFO
  #     - CONTROLLER_ID=0
  #     - RABBITMQ_HOST=rabbitmq-message-middleware
  #     - PREV_CONTROLLERS_AMOUNT=1
  #     - FILTERS_AMOUNT=1
  #     - MAPS_AMOUNT=1
  #     - YEARS=2024,2025
  #   networks:
  #     - custom_net
  #   depends_on:
  #     rabbitmq-message-middleware:
  #       condition: service_healthy

  # ============================== OUTPUT BUILDER SERVICES ============================== #

  query_1x_output_builder_0:
    container_name: query_1x_output_builder_0
    image: query_1x_output_builder:latest
    entrypoint: python3 -m controllers.output_builders.query_1x_output_builder.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - OUTPUT_BUILDER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - PREV_CONTROLLERS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  query_21_output_builder_0:
    container_name: query_21_output_builder_0
    image: query_21_output_builder:latest
    entrypoint: python3 -m controllers.output_builders.query_21_output_builder.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - OUTPUT_BUILDER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - PREV_CONTROLLERS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  query_22_output_builder_0:
    container_name: query_22_output_builder_0
    image: query_22_output_builder:latest
    entrypoint: python3 -m controllers.output_builders.query_22_output_builder.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - OUTPUT_BUILDER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - PREV_CONTROLLERS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  query_3x_output_builder_0:
    container_name: query_3x_output_builder_0
    image: query_3x_output_builder:latest
    entrypoint: python3 -m controllers.output_builders.query_3x_output_builder.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - OUTPUT_BUILDER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - PREV_CONTROLLERS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

  query_4x_output_builder_0:
    container_name: query_4x_output_builder_0
    image: query_4x_output_builder:latest
    entrypoint: python3 -m controllers.output_builders.query_4x_output_builder.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
      - OUTPUT_BUILDER_ID=0
      - RABBITMQ_HOST=rabbitmq-message-middleware
      - PREV_CONTROLLERS_AMOUNT=1
    networks:
      - custom_net
    depends_on:
      rabbitmq-message-middleware:
        condition: service_healthy

networks:
  custom_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24