name: tp
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 -m server.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - SERVER_PORT=5000
      - SERVER_LISTEN_BACKLOG=5
    networks:
      - custom_net

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 -m client.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CLIENT_ID=1
      - SERVER_HOST=server
      - SERVER_PORT=5000
      - DATA_PATH=/data
      - BATCH_MAX_SIZE=1
    networks:
      - custom_net
    volumes:
      - type: bind
        source: ./.data
        target: /data
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      server:
        condition: service_started

  filter_by_year:
    container_name: filter_by_year
    image: filter_by_year:latest
    entrypoint: python3 -m filter_by_year.main
    working_dir: /filter_by_year
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - YEARS=2024,2025
    networks:
      - custom_net
    volumes:
      - type: bind
        source: ./.data/transaction_items
        target: /filter_by_year/data
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1

  filter_by_hour:
    container_name: filter_by_hour
    image: filter_by_hour:latest
    entrypoint: python3 -m filter_by_hour.main
    working_dir: /filter_by_hour
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - MIN_HOUR=6
      - MAX_HOUR=23
    networks:
      - custom_net
    volumes:
      - type: bind
        source: ./.data/transactions
        target: /filter_by_hour/data
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1

  filter_by_amount:
    container_name: filter_by_amount
    image: filter_by_amount:latest
    entrypoint: python3 -m filter_by_amount.main
    working_dir: /filter_by_amount
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - AMOUNT=75
    networks:
      - custom_net
    volumes:
      - type: bind
        source: ./.data/transactions
        target: /filter_by_amount/data
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1


networks:
  custom_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
