name: tp
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 -m server.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - SERVER_PORT=5000
      - SERVER_LISTEN_BACKLOG=5
    networks:
      - custom_net

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 -m client.main
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CLIENT_ID=1
      - SERVER_HOST=server
      - SERVER_PORT=5000
      - DATA_PATH=/agency-1.csv
      - BATCH_MAX_KIB=8
    networks:
      - custom_net
    volumes:
      - type: bind
        source: ./.data/agency-1.csv
        target: /agency-1.csv
        read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
    depends_on:
      server:
        condition: service_started

networks:
  custom_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
