name: devcontainer

services:
  rabbitmq-dev:
    image: "rabbitmq:4-management" # can be slim image
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - devcontainer_net
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - rabbitmq-dev
    networks:
      - devcontainer_net

networks:
  devcontainer_net:
    driver: bridge